title: Tralsys
description: Train Supplies Link System
theme: just-the-docs

url: https://tralsys.github.io

heading_anchors: true
color_scheme: dark

plugins:
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-optional-front-matter

defaults:
  -
    scode:
      path: ""
      type: "pages"
    values:
      layout: "default"

optional_front_matter:
  remove_originals: true
